package MainPackage;
import FileMenu.ToDoList;
import FileMenu.search;
import FileMenu.Calc;
import FileMenu.NotificationBoard;
import FileMenu.Game;
import UserSetting.TimeDate;
import SomeFunctions.MyConnection;
import UserSetting.Background;
import UserSetting.LoginFrame;
import UserSetting.UserSetting;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public final class MainFrame extends javax.swing.JFrame {
    
    public MainFrame() {   
        
        initComponents();      
        this.setLocationRelativeTo(null);          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabelBackround = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSearch = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuCalc = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSignOut = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuStudentRegistration = new javax.swing.JMenuItem();
        jMenuResultCalc = new javax.swing.JMenuItem();
        jMenuStudentResult = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuTeacherRegistration = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemGreen = new javax.swing.JMenuItem();
        jMenuItemWhite = new javax.swing.JMenuItem();
        jMenuItemDefault = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Management");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelBackround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Back.jpg"))); // NOI18N
        getContentPane().add(jLabelBackround, new java.awt.GridBagConstraints());

        jMenuBar1.setBackground(new java.awt.Color(15, 15, 15));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(254, 254, 254));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFocusCycleRoot(true);
        jMenuBar1.setFocusTraversalPolicyProvider(true);
        jMenuBar1.setFocusable(false);
        jMenuBar1.setOpaque(false);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(322, 40));

        jMenu1.setText(" File");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        jMenuSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/sea.png"))); // NOI18N
        jMenuSearch.setText("Search System");
        jMenuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSearchActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSearch);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ToDo.png"))); // NOI18N
        jMenuItem8.setText("Notification Board");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuCalc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCalc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/calc.png"))); // NOI18N
        jMenuCalc.setText("Calculator");
        jMenuCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCalcActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCalc);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/game.png"))); // NOI18N
        jMenuItem1.setText("Game");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuSignOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuSignOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/signOut.png"))); // NOI18N
        jMenuSignOut.setText("SignOut");
        jMenuSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSignOutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSignOut);

        jMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ex.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        jMenu3.setBackground(new java.awt.Color(204, 255, 204));
        jMenu3.setText(" Student");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        jMenuStudentRegistration.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuStudentRegistration.setBackground(new java.awt.Color(255, 255, 255));
        jMenuStudentRegistration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuStudentRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/AddStudent.png"))); // NOI18N
        jMenuStudentRegistration.setText("Registration");
        jMenuStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStudentRegistrationActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuStudentRegistration);

        jMenuResultCalc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuResultCalc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuResultCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Result.png"))); // NOI18N
        jMenuResultCalc.setText("Result Calc");
        jMenuResultCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuResultCalcActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuResultCalc);

        jMenuStudentResult.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuStudentResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuStudentResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Marks.png"))); // NOI18N
        jMenuStudentResult.setText("Results");
        jMenuStudentResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStudentResultActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuStudentResult);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ToDo.png"))); // NOI18N
        jMenuItem7.setText("ToDo List");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setText(" Teachers");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuTeacherRegistration.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuTeacherRegistration.setBackground(new java.awt.Color(48, 48, 48));
        jMenuTeacherRegistration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuTeacherRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/AddStudent.png"))); // NOI18N
        jMenuTeacherRegistration.setText("Resgistration");
        jMenuTeacherRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuTeacherRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTeacherRegistrationActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuTeacherRegistration);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Result.png"))); // NOI18N
        jMenuItem6.setText("TimeTable");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ToDo.png"))); // NOI18N
        jMenuItem3.setText("ToDo List");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu7.setText(" Setting");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/settingUser.png"))); // NOI18N
        jMenuItem4.setText("User Setting");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/setting.png"))); // NOI18N
        jMenuItem5.setText("Time & Date");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/color.png"))); // NOI18N
        jMenu2.setText("Background");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItemGreen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemGreen.setText("Change Background ");
        jMenuItemGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGreenActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemGreen);

        jMenuItemWhite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemWhite.setText("White");
        jMenuItemWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWhiteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemWhite);

        jMenuItemDefault.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemDefault.setForeground(new java.awt.Color(0, 102, 0));
        jMenuItemDefault.setText("Default");
        jMenuItemDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDefaultActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDefault);

        jMenu7.add(jMenu2);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/theme.png"))); // NOI18N
        jMenu6.setText("Theme");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Theme 2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenu7.add(jMenu6);

        jMenuBar1.add(jMenu7);

        jMenu5.setText(" About");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Calc calc = new Calc();
    Frame frame = new Frame();
    search searchO = new search();
    Game game = new Game();
     ToDoList todo = new ToDoList();
    UserSetting us = new UserSetting();
    NotificationBoard nb = new NotificationBoard();
    StudentRegistration manageO = new StudentRegistration();
    TeacherRegistrations teacher = new TeacherRegistrations();
    ResultTable rt = new ResultTable();
    LoginFrame Login = new LoginFrame();
    private void jMenuCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCalcActionPerformed
        calc.setVisible(true);
        calc.pack();
        calc.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuCalcActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSignOutActionPerformed
        this.dispose();
        calc.dispose();
        teacher.dispose();
        frame.dispose();
        game.dispose();
        todo.dispose();
        tt.dispose();
        back.dispose();
        rt.dispose();
        us.dispose();
        nb.dispose();
        searchO.dispose();
        manageO.dispose();
        Login.setVisible(true);
        Login.pack();
        Login.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jMenuSignOutActionPerformed

    private void jMenuStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStudentRegistrationActionPerformed
        manageO.setVisible(true);
        manageO.pack();
        manageO.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuStudentRegistrationActionPerformed

    private void jMenuResultCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuResultCalcActionPerformed
        frame.setVisible(true);
        frame.pack();
        frame.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_jMenuResultCalcActionPerformed

    private void jMenuTeacherRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTeacherRegistrationActionPerformed
        teacher.setVisible(true);
        teacher.pack();
        teacher.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuTeacherRegistrationActionPerformed

    private void jMenuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSearchActionPerformed
        searchO.setVisible(true);
        searchO.pack();
        searchO.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuSearchActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        game.setVisible(true);
        game.pack();
        game.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
     
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        AboutDetail about = new AboutDetail();
        about.setVisible(true);
        about.pack();
        about.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         MainFrame2 mf2 = new MainFrame2();
        mf2.setVisible(true);
        mf2.pack();
        mf2.setLocationRelativeTo(null);
        mf2.setExtendedState(MainFrame2.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
        
    private void jMenuStudentResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStudentResultActionPerformed
        rt.setVisible(true);
        rt.pack();
        rt.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jMenuStudentResultActionPerformed

        int a = 2;        
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        String Query = "SELECT loginAs FROM login WHERE loginAs ='Principle'";
        PreparedStatement ps;
        ResultSet rs;
        try{
            ps = MyConnection.getConnection().prepareStatement(Query);
            rs = ps.executeQuery();
            rs.next();
            if(rs.getString("loginAs").equals(LoginFrame.SeeUser)){
                us.setVisible(true);
                us.setLocationRelativeTo(null);
            }else
                JOptionPane.showMessageDialog(null, "Only Admin Can Manipulate User Setting!");    
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Please Try After Some Time!"+e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginAsTeacher();
        LoginAsStudent();
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        nb.setVisible(true);
        nb.pack();
        nb.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem8ActionPerformed
        TimeTable tt = new TimeTable();
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        tt.setVisible(true);
        tt.setLocationRelativeTo(null);
        tt.pack();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        todo.setVisible(true);
        todo.pack();
        todo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        todo.setVisible(true);
        todo.pack();
        todo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem7ActionPerformed
        Background back = new Background();
    private void jMenuItemGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGreenActionPerformed
        back.setVisible(true);
        back.pack();
        back.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jMenuItemGreenActionPerformed

    private void jMenuItemWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWhiteActionPerformed
       
        jLabelBackround.setIcon(new ImageIcon("/home/hadi/NetBeansProjects/student/src/Picture/ba.jpeg"));
    }//GEN-LAST:event_jMenuItemWhiteActionPerformed

    private void jMenuItemDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDefaultActionPerformed
        jLabelBackround.setIcon(new ImageIcon("/home/hadi/NetBeansProjects/student/src/Picture/Back.jpg"));
        
    }//GEN-LAST:event_jMenuItemDefaultActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        TimeDate time = new TimeDate();
        time.setVisible(true);
        time.setLocationRelativeTo(null);
        time.pack();;
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void LoginAsStudent(){
        // ======================When YOu Login As Student =============================
        String Query = "SELECT loginAs FROM login WHERE loginAs ='Student'";
        PreparedStatement ps;
        ResultSet rs;
        try{
            ps = MyConnection.getConnection().prepareStatement(Query);
            rs = ps.executeQuery();
            rs.next();
            if(LoginFrame.SeeUser.equals(rs.getString("loginAs"))){
                jMenu4.setEnabled(false);
                jMenuStudentRegistration.setEnabled(false);
                jMenuResultCalc.setEnabled(false);
            }
        }catch(Exception e){
        }
// =============================================================================
    }
    private void LoginAsTeacher(){
        // ======================When YOu Login As Teacher =============================
        String Query2 = "SELECT loginAs FROM login WHERE loginAs ='Teacher'";
        PreparedStatement s;
        ResultSet r;
        try{
            s = MyConnection.getConnection().prepareStatement(Query2);
            r = s.executeQuery();
            r.next();
            if(LoginFrame.SeeUser.equals(r.getString("loginAs")))
                jMenuTeacherRegistration.setEnabled(false);
                
        }catch(Exception e){
        }
// =============================================================================
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabelBackround;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCalc;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemDefault;
    private javax.swing.JMenuItem jMenuItemGreen;
    private javax.swing.JMenuItem jMenuItemWhite;
    private javax.swing.JMenuItem jMenuResultCalc;
    private javax.swing.JMenuItem jMenuSearch;
    private javax.swing.JMenuItem jMenuSignOut;
    private javax.swing.JMenuItem jMenuStudentRegistration;
    private javax.swing.JMenuItem jMenuStudentResult;
    private javax.swing.JMenuItem jMenuTeacherRegistration;
    // End of variables declaration//GEN-END:variables
}
