package MainPackage;


//import static ResultTable.Student_Id;
import SomeFunctions.MyConnection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static SomeFunctions.Helper.AlreadyExist;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Hadi
 */
public class StudentRegistration extends javax.swing.JFrame {
    PreparedStatement ps;
        ResultSet rs;
    public StudentRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonF = new javax.swing.JRadioButton();
        jRadioButtonM = new javax.swing.JRadioButton();
        jTextLName = new javax.swing.JTextField();
        jTextName = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jButtonAdd = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStudentName = new javax.swing.JTable();
        jTextFieldSearch = new javax.swing.JTextField();
        jTextBirth = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextPhone = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFees = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxCourse = new javax.swing.JComboBox();
        jButtonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fees:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 70, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BirthDay: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PhoneNo: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 380, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Address: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 30));

        jRadioButtonF.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(jRadioButtonF);
        jRadioButtonF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonF.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonF.setText("Female");
        jPanel1.add(jRadioButtonF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jRadioButtonM.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(jRadioButtonM);
        jRadioButtonM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonM.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonM.setText("Male");
        jRadioButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));
        jPanel1.add(jTextLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 220, 30));

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 220, 30));

        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });
        jTextId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextIdKeyTyped(evt);
            }
        });
        jPanel1.add(jTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 220, 30));

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 260, 83));

        jButtonAdd.setBackground(new java.awt.Color(254, 254, 254));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(17, 17, 17));
        jButtonAdd.setText("Delete");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddMouseExited(evt);
            }
        });
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 90, 39));

        jButtonSave.setBackground(new java.awt.Color(238, 238, 238));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(19, 19, 19));
        jButtonSave.setText("Save");
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSaveMouseExited(evt);
            }
        });
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 90, 40));

        jButtonRegister.setBackground(new java.awt.Color(254, 254, 254));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(17, 17, 17));
        jButtonRegister.setText("Register");
        jButtonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegisterMouseExited(evt);
            }
        });
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 100, 39));

        jTableStudentName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableStudentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableStudentName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Std_Id", "FName", "LName", "Gender", "Course", "Fees", "BirthDay", "Phone", "Address"
            }
        ));
        jTableStudentName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableStudentName.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableStudentName.setName(""); // NOI18N
        jTableStudentName.setRowHeight(20);
        jTableStudentName.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTableStudentName.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTableStudentNameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTableStudentName);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 610, 470));

        jTextFieldSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldSearch.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldSearch.setText("search");
        jTextFieldSearch.setToolTipText("");
        jTextFieldSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchFocusLost(evt);
            }
        });
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 610, 40));
        jPanel1.add(jTextBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 230, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gender:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 90, -1));

        jTextPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPhoneActionPerformed(evt);
            }
        });
        jTextPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPhoneKeyTyped(evt);
            }
        });
        jPanel1.add(jTextPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 230, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 990, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Student");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Student_Id:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));
        jPanel1.add(jTextFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 230, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Course:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 30));

        jComboBoxCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BTech IT", "BTech SE", "BTech Civil", "BTech EE", " " }));
        jPanel1.add(jComboBoxCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 220, 30));

        jButtonEdit.setBackground(new java.awt.Color(254, 254, 254));
        jButtonEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(21, 21, 21));
        jButtonEdit.setText("Edit");
        jButtonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditMouseExited(evt);
            }
        });
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 80, 39));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMActionPerformed

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jTextIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextIdKeyTyped
        
    }//GEN-LAST:event_jTextIdKeyTyped

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        if(jTableStudentName.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"First Select A Row To Be Edited");
        }
        else if(jTableStudentName.getSelectedRow()!=-1){
            if(jTextId.getText().equals("")||jTextName.getText().equals("")
                    ||jTextLName.getText().equals("")||jTextFees.getText().equals("")
                    ||jTextBirth.getText().equals("")||jTextPhone.getText().equals("")
                    ||jTextAreaAddress.getText().equals("")||jComboBoxCourse.getSelectedItem().equals(""))
                JOptionPane.showMessageDialog(null,"The data is Already Saved!");
            else{
            String combo = jComboBoxCourse.getSelectedItem().toString();
        String id = jTableStudentName.getValueAt(jTableStudentName.getSelectedRow(), 0).toString();
        String Query = "UPDATE student_reg SET student_id = '"+jTextId.getText()+"',"
                + " FirstName='"+jTextName.getText()+"',"
                + " LastName='"+jTextLName.getText()+"',"
                + " Gender='"+RadioButton()+"',"
                + " Course='"+combo+"',"
                + " Fee='"+jTextFees.getText()+"',"
                + " BirthDay='"+jTextBirth.getText()+"',"
                + " Phone='"+jTextPhone.getText()+"',"
                + " Address='"+jTextAreaAddress.getText()+"'"
                + " WHERE student_id = "+'"'+id+'"';
        
        if(!AlreadyExist(jTextId.getText())){
        try{
            ps = MyConnection.getConnection().prepareStatement(Query);
            ps.executeUpdate();
            DeletePreEditedRowFromTable();
            RegisterTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Can not Edit at this Time Please Try Later!"+e.getMessage()); 

        }
        }
        }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    public void DeletePreEditedRowFromTable (){
        DefaultTableModel model = (DefaultTableModel) jTableStudentName.getModel();
        model.removeRow(jTableStudentName.getSelectedRow());
    }
        
    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed

        if(jTextId.getText().trim().equals("")
               ||jTextName.getText().trim().equals("")
               ||jTextLName.getText().trim().equals(""))
           JOptionPane.showMessageDialog(null, "Please Enter student Name and Id", "Alert",1);
       else if(jTextBirth.getText().isEmpty()||jTextPhone.getText().isEmpty()
               ||jTextAreaAddress.getText().isEmpty()||jTextFees.getText().isEmpty())
           JOptionPane.showMessageDialog(null, "Please Enter the Details","Alert",1);
        
       else{
        String ID = jTextId.getText();
        if(!AlreadyExist(ID)){
        String query = "insert into student_reg(student_id, firstName, lastName, Gender, Course, Fee, birthDay, Phone, Address) values(?,?,?,?,?,?,?,?,?)";
        
        try{
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, ID);
            ps.setString(2, jTextName.getText());
            ps.setString(3, jTextLName.getText());
            ps.setString(4, RadioButton());
            ps.setString(5, jComboBoxCourse.getSelectedItem().toString());
            ps.setString(6, jTextFees.getText());
            ps.setString(7, jTextBirth.getText());
            ps.setString(8, jTextPhone.getText());
            ps.setString(9, jTextAreaAddress.getText());
            ps.executeUpdate();
            RegisterTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Can not Store tha data at this Time Please Try Later!"+e.getMessage()); 

        }        
        }
    }
        
        
    }//GEN-LAST:event_jButtonRegisterActionPerformed
//============================Some Functions====================================
    public String RadioButton(){
        if(jRadioButtonM.isSelected())
            return jRadioButtonM.getText();
        else
            return jRadioButtonF.getText();
    }
    
    private Object RegisterTable(){
        DefaultTableModel model = (DefaultTableModel) jTableStudentName.getModel();
       model.addRow(new Object[]{
           jTextId.getText(),
           jTextName.getText(),
           jTextLName.getText(),
           RadioButton(),
           jComboBoxCourse.getSelectedItem(),
           jTextFees.getText(),
           jTextBirth.getText(),
           jTextPhone.getText(),
           jTextAreaAddress.getText()           
       });
       return 0;
    }
    //==========================================================================
    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jTableStudentNameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableStudentNameAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableStudentNameAncestorAdded

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
          DefaultTableModel model = (DefaultTableModel) jTableStudentName.getModel();
        if(jTableStudentName.getSelectedRow()==-1){
            if(jTableStudentName.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No Student has been Selected",
                        "Alert!", JOptionPane.OK_OPTION);
            }else
                JOptionPane.showMessageDialog(null, "Select the student to be Deleted",
                        "Student Records System", JOptionPane.OK_OPTION);
            
        }
        else{        
            String id = jTableStudentName.getValueAt(jTableStudentName.getSelectedRow(), 0).toString();
            try{
            ps = MyConnection.getConnection().prepareStatement("DELETE FROM student_reg WHERE(student_id ="+'"'+id+'"'+")");
            ps.executeUpdate();
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Can Not Delete At this Moment! Try Later"+e.getMessage());
            }
            model.removeRow(jTableStudentName.getSelectedRow());
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPhoneActionPerformed

    private void jTextPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPhoneKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPhoneKeyTyped

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jTextFieldSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchFocusGained
        if(jTextFieldSearch.getText().trim().toLowerCase().equals("search")){
            jTextFieldSearch.setText("");
            jTextFieldSearch.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_jTextFieldSearchFocusGained

    private void jTextFieldSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchFocusLost
        if(jTextFieldSearch.getText().trim().equals("")||
                jTextFieldSearch.getText().trim().toLowerCase().equals("search"))
            jTextFieldSearch.setText("Search");            
            jTextFieldSearch.setForeground(new Color(153,153,153,153));
            
    }//GEN-LAST:event_jTextFieldSearchFocusLost
       
    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
               
         if(jTableStudentName.getSelectedRow()==-1)
    JOptionPane.showMessageDialog(null,"Please Select a Row to Edit!");
    else{
        jTextId.setText(jTableStudentName.getValueAt(jTableStudentName.getSelectedRow(), 0).toString());
        jTextName.setText(jTableStudentName.getValueAt(jTableStudentName.getSelectedRow(), 1).toString());
        jTextLName.setText(jTableStudentName.getValueAt(jTableStudentName.getSelectedRow(), 2).toString());
        jTextFees.setText(jTableStudentName.getValueAt(jTableStudentName.getSelectedRow(), 5).toString());
        jTextBirth.setText(jTableStudentName.getValueAt(jTableStudentName.getSelectedRow(), 6).toString());
        jTextPhone.setText(jTableStudentName.getValueAt(jTableStudentName.getSelectedRow(), 7).toString());
        jTextAreaAddress.setText(jTableStudentName.getValueAt(jTableStudentName.getSelectedRow(), 8).toString());
}
        
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            String registerQuery ="SELECT * From student_reg";
            DefaultTableModel modele = (DefaultTableModel) jTableStudentName.getModel();        
            ps = MyConnection.getConnection().prepareStatement(registerQuery);
            rs = ps.executeQuery();
            while(rs.next()){
            Object o[]= {rs.getString("student_id"), rs.getString("firstName"), rs.getString("lastName")
                    ,rs.getString("Gender"), rs.getString("Course"), rs.getString("Fee")
                    ,rs.getString("BirthDay"), rs.getString("Phone"), rs.getString("Address")};
            if(jTableStudentName.getRowCount()!= getRowNumber())    
            modele.addRow(o);    
            }
            }catch(SQLException ex){
              Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_formWindowOpened

    private void jButtonRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterMouseEntered
        jButtonRegister.setBackground(Color.BLACK);
        jButtonRegister.setForeground(Color.white);
    }//GEN-LAST:event_jButtonRegisterMouseEntered

    private void jButtonRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterMouseExited
        jButtonRegister.setBackground(Color.white);
        jButtonRegister.setForeground(Color.black);
    }//GEN-LAST:event_jButtonRegisterMouseExited

    private void jButtonAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseEntered
        jButtonAdd.setBackground(Color.black);
        jButtonAdd.setForeground(Color.white);
    }//GEN-LAST:event_jButtonAddMouseEntered

    private void jButtonAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseExited
        jButtonAdd.setBackground(Color.white);
        jButtonAdd.setForeground(Color.black);
    }//GEN-LAST:event_jButtonAddMouseExited

    private void jButtonSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveMouseEntered
        jButtonSave.setBackground(Color.black);
        jButtonSave.setForeground(Color.white);
    }//GEN-LAST:event_jButtonSaveMouseEntered

    private void jButtonSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveMouseExited
        jButtonSave.setBackground(Color.white);
        jButtonSave.setForeground(Color.black);
    }//GEN-LAST:event_jButtonSaveMouseExited

    private void jButtonEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseEntered
        jButtonEdit.setBackground(Color.black);
        jButtonEdit.setForeground(Color.white);
    }//GEN-LAST:event_jButtonEditMouseEntered

    private void jButtonEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseExited
        jButtonEdit.setBackground(Color.white);
        jButtonEdit.setForeground(Color.black);
    }//GEN-LAST:event_jButtonEditMouseExited

    public int getRowNumber(){//============start===============

    int numberRow = 0;
    PreparedStatement ps;
    ResultSet rs;
    String query = "select count(*) from student_reg";
        try{
            ps = MyConnection.getConnection().prepareStatement(query);
            rs = ps.executeQuery();
            while(rs.next()){
                numberRow = rs.getInt("count(*)");
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Error ");
        }
    return numberRow;
}//===========================end================================
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StudentRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonF;
    private javax.swing.JRadioButton jRadioButtonM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTableStudentName;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextBirth;
    private javax.swing.JTextField jTextFees;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextLName;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPhone;
    // End of variables declaration//GEN-END:variables
}
