/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import SomeFunctions.MyConnection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hadi
 */
public class ToDoList extends javax.swing.JFrame {

    /**
     * Creates new form ToDoList
     */
    public ToDoList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableToDo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextFieldTask = new javax.swing.JTextField();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldTime = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextNo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableToDo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTableToDo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Task", "Date", "Time"
            }
        ));
        jTableToDo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableToDo.setFocusable(false);
        jTableToDo.setOpaque(false);
        jTableToDo.setRowHeight(30);
        jTableToDo.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTableToDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableToDoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableToDo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 770, 370));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 38));

        jTextFieldTask.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldTask.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldTask.setText("Task");
        jTextFieldTask.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTaskFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTaskFocusLost(evt);
            }
        });
        getContentPane().add(jTextFieldTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 189, 38));

        jTextFieldDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldDate.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldDate.setText("yyyy/mm/dd");
        jTextFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusLost(evt);
            }
        });
        getContentPane().add(jTextFieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 177, 38));

        jTextFieldTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldTime.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldTime.setText("hh:mm:ss");
        jTextFieldTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTimeFocusLost(evt);
            }
        });
        getContentPane().add(jTextFieldTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 146, 38));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 38));

        jTextNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextNo.setForeground(new java.awt.Color(153, 153, 153));
        jTextNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNo.setText("NO");
        jTextNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNoFocusLost(evt);
            }
        });
        jTextNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 45, 38));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ex.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 50, 38));

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 110, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TO DO LIST");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextFieldTask.setVisible(false);
        jTextFieldDate.setVisible(false);
        jTextFieldTime.setVisible(false);
        jTextNo.setVisible(false);
        jButton2.setVisible(false);
        jButtonDelete.setVisible(false);
                
        try {
            String registerQuery ="SELECT * From todo";
            DefaultTableModel modele = (DefaultTableModel) jTableToDo.getModel();
            PreparedStatement ps;
            ResultSet rs;
            ps = MyConnection.getConnection().prepareStatement(registerQuery);
            rs = ps.executeQuery();
            while(rs.next()){
            Object o[]= {rs.getString("No"), rs.getString("Task"), rs.getString("Date")
                    ,rs.getString("Time")};
            if(jTableToDo.getRowCount()!= getRowNumber())    
            modele.addRow(o);    
            }
            }catch(SQLException ex){
              JOptionPane.showMessageDialog(null,"Please Restart Or Try Again Later! ");
            }
        
    }//GEN-LAST:event_formWindowOpened
    public int getRowNumber(){//============start===============================
    int numberRow = 0;
    PreparedStatement ps;
    ResultSet rs;
    String query = "select count(*) from todo";
        try{
            ps = MyConnection.getConnection().prepareStatement(query);
            rs = ps.executeQuery();
            while(rs.next()){
                numberRow = rs.getInt("count(*)");
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Error ");
        }
    return numberRow;
}//===========================end===============================================   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNoFocusLost

        if(jTextNo.getText().trim().equals("")||
            jTextNo.getText().trim().toUpperCase().equals("NO")){
            jTextNo.setText("NO");
            jTextNo.setForeground(new Color(153,153,153,153));
        }
    }//GEN-LAST:event_jTextNoFocusLost

    private void jTextNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNoFocusGained
        if(jTextNo.getText().trim().toUpperCase().equals("NO")){
            jTextNo.setText("");
            jTextNo.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextNoFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextFieldTask.setVisible(true);
        jTextFieldDate.setVisible(true);
        jTextFieldTime.setVisible(true);
        jTextNo.setVisible(true);
        jButton2.setVisible(true);
        jButtonDelete.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String No = jTextNo.getText();
        String Task = jTextFieldTask.getText();
        String Date = jTextFieldDate.getText();
        String Time = jTextFieldTime.getText();

        String Query = "INSERT INTO todo (No, Task, Date, Time)"
        + " VALUES(?,?,?,?)";
        PreparedStatement ps;
        ResultSet rs;
        try{
            ps = MyConnection.getConnection().prepareStatement(Query);
            ps.setString(1, No);
            ps.setString(2, Task);
            ps.setString(3, Date);
            ps.setString(4, Time);
            ps.executeUpdate();

            DefaultTableModel model = (DefaultTableModel) jTableToDo.getModel();
            model.addRow(new Object[]{
                jTextNo.getText(),
                jTextFieldTask.getText(),
                jTextFieldDate.getText(),
                jTextFieldTime.getText()
            });

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"First Enter the Date Then Save!");
        }

        jTextFieldTask.setVisible(false);
        jTextFieldDate.setVisible(false);
        jTextFieldTime.setVisible(false);
        jTextNo.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNoActionPerformed

    private void jTextFieldTaskFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTaskFocusGained
        if(jTextFieldTask.getText().trim().equals("Task")){
            jTextFieldTask.setText("");
            jTextFieldTask.setForeground(Color.black);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaskFocusGained

    private void jTextFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusGained
        if(jTextFieldDate.getText().trim().equals("yyyy/mm/dd")){
            jTextFieldDate.setText("");
            jTextFieldDate.setForeground(Color.black);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateFocusGained

    private void jTextFieldTimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTimeFocusGained
        if(jTextFieldTime.getText().trim().equals("hh:mm:ss")){
            jTextFieldTime.setText("");
            jTextFieldTime.setForeground(Color.black);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeFocusGained

    private void jTextFieldTaskFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTaskFocusLost
        if(jTextFieldTask.getText().trim().equals("")||
            jTextFieldTask.getText().trim().equals("Task")){
            jTextFieldTask.setText("Task");
            jTextFieldTask.setForeground(new Color(153,153,153,153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaskFocusLost

    private void jTextFieldDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusLost
        if(jTextFieldDate.getText().trim().equals("")||
            jTextFieldDate.getText().trim().equals("yyyy/mm/dd")){
            jTextFieldDate.setText("yyyy/mm/dd");
            jTextFieldDate.setForeground(new Color(153,153,153,153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateFocusLost

    private void jTextFieldTimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTimeFocusLost
        if(jTextFieldTime.getText().trim().equals("")||
            jTextFieldTime.getText().trim().equals("hh:mm:ss")){
            jTextFieldTime.setText("hh:mm:ss");
            jTextFieldTime.setForeground(new Color(153,153,153,153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeFocusLost

    private void jTableToDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableToDoMouseClicked
        jTextNo.setVisible(false);
        jTextFieldTask.setVisible(false);
        jTextFieldDate.setVisible(false);
        jTextFieldTime.setVisible(false);
        jButtonDelete.setVisible(true);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableToDoMouseClicked

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableToDo.getModel();
        String id = jTableToDo.getValueAt(jTableToDo.getSelectedRow(), 0).toString();
        PreparedStatement ps;
        ResultSet rs;        
        try{
            ps = MyConnection.getConnection().prepareStatement("DELETE FROM todo WHERE(No ="+'"'+id+'"'+")");
            ps.executeUpdate();
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Can Not Delete At this Moment! Try Later"+e.getMessage());
            }
            model.removeRow(jTableToDo.getSelectedRow());
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToDoList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableToDo;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldTask;
    private javax.swing.JTextField jTextFieldTime;
    private javax.swing.JTextField jTextNo;
    // End of variables declaration//GEN-END:variables
}
